// Angular/src/app/edit-row-template/edit-row-template.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter
} from '@angular/core';
import { DataRowTemplateData } from 'devextreme/ui/data_grid';
import { ValueChanged } from '../app.service';

@Component({
  selector: 'edit-row-template',
  templateUrl: './edit-row-template.component.html',
  styleUrls: ['./edit-row-template.component.scss'],
})
export class EditRowTemplateComponent {
  @Input() employee!: DataRowTemplateData;

  @Output() onSaveButtonClick = new EventEmitter<number>();

  @Output() onCancelButtonClick = new EventEmitter<number>();

  @Output() onValueChanged = new EventEmitter<ValueChanged>();

  editors: string[] = ['Prefix', 'FirstName', 'LastName', 'Position', 'BirthDate', 'HireDate'];

  saveButtonClick(): void {
    this.onSaveButtonClick.emit();
  }

  cancelButtonClick(): void {
    this.onCancelButtonClick.emit();
  }

  valueChanged(e: any, dataField: string, key: number): void {
    this.onValueChanged.emit({ e, dataField, key });
  }
}

<ng-container>
  <tr class="main-row">
    <td *ngFor="let editor of editors">
      <div *ngIf="editor != 'BirthDate' && editor != 'HireDate'; else datebox">
        <dx-text-box
          [value]="employee.data[editor]"
          (onValueChanged)="
            valueChanged({ e: $event, dataField: editor, key: employee.key })
          "
        ></dx-text-box>
      </div>
      <ng-template #datebox>
        <dx-date-box
          [value]="employee.data[editor]"
          (onValueChanged)="
            valueChanged({ e: $event, dataField: editor, key: employee.key })
          "
        ></dx-date-box>
      </ng-template>
    </td>
    <td rowSpan="2">
      <dx-button text="Save" (onClick)="saveButtonClick()"></dx-button>
      <dx-button text="Cancel" (onClick)="cancelButtonClick()"> </dx-button>
    </td>
  </tr>
  <tr class="notes-row">
    <td colspan="6">
      <dx-text-area
        [value]="employee.data.Notes"
        (onValueChanged)="
          valueChanged({ e: $event, dataField: 'Notes', key: employee.key })
        "
      ></dx-text-area>
    </td>
  </tr>
</ng-container>

// Vue/src/components/EditRowTemplate.vue
<script setup lang="ts">
import { DxButton, DxTextBox, DxDateBox, DxTextArea } from 'devextreme-vue';
import type { DataRowTemplateData } from 'devextreme/ui/data_grid';
withDefaults(defineProps<{ rowInfo: DataRowTemplateData }>(), {
  rowInfo: undefined,
});
defineEmits(['onValueChanged', 'onSaveButtonClick', 'onCancelButtonClick']);
const editors: string[] = [
  'Prefix',
  'FirstName',
  'LastName',
  'Position',
  'BirthDate',
  'HireDate',
];
</script>

<template>
  <div style="display: contents">
    <tr class="main-row">
      <td
        v-for="editor in editors"
        :key="editor"
      >
        <div v-if="editor != 'BirthDate' && editor != 'HireDate'">
          <DxTextBox
            :value="rowInfo!.data[editor]"
            @value-changed="
              $emit('onValueChanged', $event, editor, rowInfo!.data.ID)
            "
          />
        </div>
        <div v-else>
          <DxDateBox
            :value="rowInfo!.data[editor]"
            @value-changed="
              $emit('onValueChanged', $event, editor, rowInfo!.data.ID)
            "
          />
        </div>
      </td>
      <td rowSpan="2">
        <DxButton
          text="Save"
          @click="$emit('onSaveButtonClick')"
        />
        <DxButton
          text="Cancel"
          @click="$emit('onCancelButtonClick')"
        />
      </td>
    </tr>
    <tr class="notes-row">
      <td colspan="6">
        <DxTextArea
          :value="rowInfo!.data.Notes"
          @value-changed="
            $emit('onValueChanged', $event, 'Notes', rowInfo!.data.ID)
          "
        />
      </td>
    </tr>
  </div>
</template>
