// React/src/App.tsx
import React, { useCallback, useRef, useState } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import Button from 'devextreme-react/button';
import DataGrid, { Column, Toolbar, Item } from 'devextreme-react/data-grid';
import { InitNewRowEvent } from 'devextreme/ui/data_grid';
import { employees } from './data';
import DataRow from './DataRow';

// const formatDate = new Intl.DateTimeFormat('en-US').format;

function App(): JSX.Element {
  const dataGrid = useRef<any>(null);
  const [changes, setChanges] = useState([]);

  const onInitNewRow = useCallback((e: InitNewRowEvent): void => {
    e.data.Prefix = '';
    e.data.FirstName = '';
    e.data.LastName = '';
    e.data.Position = '';
    e.data.BirthDate = new Date('1986/07/08');
    e.data.HireDate = new Date('1986/07/08');
    e.data.Notes = '';
  }, []);

  const addNewItme = useCallback(() => {
    setTimeout(() => {
      const grid = dataGrid.current.instance;
      grid.cancelEditData();
      // grid.addRow();
      setChanges(grid.option('editing.changes'));
    });
  }, []);

  return (
    <div className='main'>
      <DataGrid
        ref={dataGrid}
        dataSource={employees}
        keyExpr='ID'
        rowAlternationEnabled={true}
        columnAutoWidth={true}
        showBorders={true}
        onInitNewRow={onInitNewRow}
        dataRowRender={DataRow}
      >
        <Column dataField='Prefix' caption='Title' width={70} />
        <Column dataField='FirstName' />
        <Column dataField='LastName' />
        <Column dataField='Position' />
        <Column dataField='BirthDate' dataType='date' />
        <Column dataField='HireDate' dataType='date' />
        <Column width={160} />
        <Toolbar>
          <Item location='after'>
            <Button text='Add new item' onClick={addNewItme} />
          </Item>
        </Toolbar>
      </DataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AppService, Employee, ValueChanged } from './app.service';
import DataGrid, { InitNewRowEvent, InitializedEvent } from 'devextreme/ui/data_grid';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  dataGrid!: DataGrid;
  employees: Employee[];
  changes: any;
  editors: string[];

  constructor(service: AppService) {
    this.employees = service.getEmployees();
    this.changes = [];
    this.editors = ['Prefix', 'FirstName', 'LastName', 'Position', 'BirthDate', 'HireDate'];
  }
  saveGridInstance(e: InitializedEvent) {
    this.dataGrid = e.component!;
  }

  onInitNewRow = (e: InitNewRowEvent) => {
    e.data.Prefix = '';
    e.data.FirstName = '';
    e.data.LastName = '';
    e.data.Position = '';
    e.data.BirthDate = new Date('1986/07/08');
    e.data.HireDate = new Date('1986/07/08');
    e.data.Notes = '';
  };

  addNewItem = () => {
    this.dataGrid.cancelEditData();
    this.dataGrid.addRow();
    this.changes = this.dataGrid.option('editing.changes');
  };

  onValueChanged = (val: ValueChanged) => {
    if (!this.changes.length) {
      this.changes.push({ data: { [val.dataField]: val.e.value }, key: val.key, type: 'update' });
    } else {
      this.changes[0].data = { ...this.changes[0].data, [val.dataField]: val.e.value };
    }
  };

  onEditButtonClick = (ID: number) => {
    const rowIndex = this.dataGrid.getRowIndexByKey(ID);
    this.dataGrid.cancelEditData();
    this.dataGrid.editRow(rowIndex);
    this.changes = this.dataGrid.option('editing.changes');
  };

  onDeleteButtonClick = (ID: number) => {
    const rowIndex = this.dataGrid.getRowIndexByKey(ID);
    this.dataGrid.deleteRow(rowIndex);
  };

  onSaveButtonClick = () => {
    this.dataGrid.option('editing.changes', this.changes);
    this.dataGrid.saveEditData();
    this.dataGrid.refresh();
  };

  onCancelButtonClick = () => {
    this.dataGrid.cancelEditData();
    this.dataGrid.refresh();
  };
}

<div class="demo-container">
  <dx-data-grid
    [dataSource]="employees"
    keyExpr="ID"
    [rowAlternationEnabled]="true"
    [columnAutoWidth]="true"
    [showBorders]="true"
    (onInitialized)="saveGridInstance($event)"
    (onInitNewRow)="onInitNewRow($event)"
    dataRowTemplate="dataRowTemplateName"
  >
    <dxi-column dataField="Prefix" caption="Title" [width]="70"></dxi-column>
    <dxi-column dataField="FirstName"></dxi-column>
    <dxi-column dataField="LastName"></dxi-column>
    <dxi-column dataField="Position"></dxi-column>
    <dxi-column dataField="BirthDate" dataType="date"></dxi-column>
    <dxi-column dataField="HireDate" dataType="date"></dxi-column>
    <dxi-column [width]="160"></dxi-column>
    <dxo-toolbar>
      <dxi-item location="after">
        <div *dxTemplate>
          <dx-button text="Add new item" (onClick)="addNewItem()"></dx-button>
        </div>
      </dxi-item>
    </dxo-toolbar>

    <ng-container *dxTemplate="let employee of 'dataRowTemplateName'">
      <ng-container *ngIf="employee.isEditing">
        <edit-row-template
          style="display: contents"
          [employee]="employee"
          (onSaveButtonClick)="onSaveButtonClick()"
          (onCancelButtonClick)="onCancelButtonClick()"
          (onValueChanged)="onValueChanged($event)"
        ></edit-row-template>
      </ng-container>
      <ng-container *ngIf="!employee.isEditing">
        <data-row-template
          style="display: contents"
          [employee]="employee"
          (onEditButtonClick)="onEditButtonClick(employee.data.ID)"
          (onDeleteButtonClick)="onDeleteButtonClick(employee.data.ID)"
        ></data-row-template>
      </ng-container>
    </ng-container>
  </dx-data-grid>
</div>
