// Vue/src/components/DataRowTemplate.vue
<script setup lang="ts">
import { DxButton } from 'devextreme-vue';
import type { DataRowTemplateData } from 'devextreme/ui/data_grid';
withDefaults(defineProps<{ rowInfo?: DataRowTemplateData }>(), {
  rowInfo: undefined,
});
defineEmits(['onEditButtonClick', 'onDeleteButtonClick']);
const formatDate = new Intl.DateTimeFormat('en-US').format;
</script>

<template>
  <div style="display: contents">
    <tr class="main-row">
      <td>{{ rowInfo!.data.Prefix }}</td>
      <td>{{ rowInfo!.data.FirstName }}</td>
      <td>{{ rowInfo!.data.LastName }}</td>
      <td>{{ rowInfo!.data.Position }}</td>
      <td>{{ formatDate(new Date(rowInfo!.data.BirthDate)) }}</td>
      <td>{{ formatDate(new Date(rowInfo!.data.HireDate)) }}</td>
      <td rowSpan="2">
        <DxButton
          text="Edit"
          @click="$emit('onEditButtonClick', rowInfo!.data.ID)"
        />
        <DxButton
          text="Delete"
          @click="$emit('onDeleteButtonClick', rowInfo!.data.ID)"
        />
      </td>
    </tr>
    <tr class="notes-row">
      <td colspan="6">
        <div>{{ rowInfo!.data.Notes }}</div>
      </td>
    </tr>
  </div>
</template>

// Angular/src/app/data-row-template/data-row-template.component.ts
import {
  Component,
  Input, Output,
  EventEmitter,
} from '@angular/core';
import { DataRowTemplateData } from 'devextreme/ui/data_grid';

@Component({
  selector: 'data-row-template',
  templateUrl: './data-row-template.component.html',
  styleUrls: ['./data-row-template.component.scss'],
})
export class DataRowTemplateComponent {
  @Input() employee!: DataRowTemplateData;

  @Output() onEditButtonClick = new EventEmitter<number>();

  @Output() onDeleteButtonClick = new EventEmitter<number>();

  editButtonClick(ID: number): void {
    this.onEditButtonClick.emit(ID);
  }

  deleteButtonClick(ID: number): void {
    this.onDeleteButtonClick.emit(ID);
  }
}

<ng-container>
  <tr class="main-row">
    <td>{{ employee.data.Prefix }}</td>
    <td>{{ employee.data.FirstName }}</td>
    <td>{{ employee.data.LastName }}</td>
    <td>{{ employee.data.Position }}</td>
    <td>{{ employee.data.BirthDate | date : "M/d/yyyy" }}</td>
    <td>{{ employee.data.HireDate | date : "M/d/yyyy" }}</td>
    <td rowSpan="2">
      <dx-button
        text="Edit"
        (onClick)="editButtonClick(employee.data.ID)"
      ></dx-button>
      <dx-button text="Delete" (onClick)="deleteButtonClick(employee.data.ID)">
      </dx-button>
    </td>
  </tr>
  <tr class="notes-row">
    <td colspan="6">
      <div>{{ employee.data.Notes }}</div>
    </td>
  </tr>
</ng-container>
